### ISSUE TITLE
Pull Request時にCIが毎回走るのはコストパフォーマンスが悪いのではないか

### ISSUE THREAD

**Issue by sudame** [tsukuba-websci/rsurn#4]
#2 で言及された内容。

## 背景
GitHub Actions はプライベートレポジトリの場合毎月2000分の無料の実行時間が与えられる[[公式](https://github.com/pricing)]が、macOSでアクションを実行した場合、Linuxの10倍の実行時間として計算される[[公式](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers)]。

Pull Requestのたびに macOS でアクションを走らせるのはコストパフォーマンスが悪いのではないか。

## 議論
実際のアクション実行には概ね次のような時間がかかる。
https://github.com/tsukuba-websci/rsurn/actions/runs/4414745203

<img width="312" alt="スクリーンショット 2023-03-14 19 41 35" src="https://user-images.githubusercontent.com/6907421/224975894-f5a2ff75-8dfe-44b8-8783-e4158fcd2085.png">

よって、秒以下を切り上げで計算した場合、1回のPull Requestあたり `(Linux * 1 + Windows * 2 + macOS * 10) = 4 * 1 + 7 * 2 + 5 * 10 = 68分` の実行時間が消費される。2000分の実行時間をフルに使えるとすれば、毎月29回はアクションを実行できる。

## 提案
仮に3日に1回何らかのPRが立ったとしても実行しきれる計算（PRのマージ時にもアクションが走るので毎日PRが立つとなると厳しい）なので、当面は問題無いと考える。

次のように提案する。

- 当面はこのままの運用
- 実行時間の不足が表面化してきたら、このレポジトリを public にする
    - 実験用のライブラリなので本来は公開されている方が適切ということもあり、publicにするのは問題無いと思われる

**Comment by Okabe-Junya** [comment]
迅速な対応ありがとうございます！！

> 仮に3日に1回何らかのPRが立ったとしても実行しきれる計算（PRのマージ時にもアクションが走るので毎日PRが立つとなると厳しい）なので、当面は問題無いと考える。

PR作成した後に対象ブランチにpushするとその度にactionsが回ってしまうんですよね...（もちろんmasterへのマージ時にも）  例えば昨日今日ですでに6回回っていてこのペースだとやばそうな気がしています。

<img width="1036" alt="スクリーンショット 2023-03-15 10 43 10" src="https://user-images.githubusercontent.com/86868255/225182910-8d0c93e5-03b1-4ed3-82c5-c871080a6e20.png">

後は引き継ぎ後に、この事実を把握していない人が回したときのリスクも大きそうかと思っています。ということなので3月中に

1. このリポジトリをパブリックにしてしまう
2. セルフホストランナーを導入し、macのactionは研究室のPCで実行させる

あたりの対応をできると嬉しいなぁと思っています。

**Comment by Okabe-Junya** [comment]
どちらかというと、「PRが作成された時に結構な頻度で回ること」が問題な気もするので、一番最初に提案した、

- PRをトリガーにしてon Linux だけ発火
- master に入るときに全OSに対して発火

もありなのではと思っています

**Comment by Okabe-Junya** [comment]
一旦解決したので閉じてしまう
