### ISSUE TITLE
[Feature]: このリポジトリをPublicにしたい

### ISSUE THREAD

**Issue by Okabe-Junya** [tsukuba-websci/rsurn#6]
### Feature description

private -> publicにする

### Motivation

vm上などでそのまま `pip install` することができず，

1. vm上でgithubの面倒な認証をやる
2. 手元のpcから `scp` （`gcloud compute scp`）をする

のような対応をする必要があり面倒だから

**Comment by Okabe-Junya** [comment]
@ciaran-regan-ie 

If it looks good to you, I will make this repository public. What do you think?

**Comment by ciaran-regan-ie** [comment]
@Okabe-Junya 

It looks like the other PolyaUrnSimulator repo is public, so it should be okay to make this public too!

**Comment by Okabe-Junya** [comment]
I made this repository!! thank you 👍
