### ISSUE TITLE
Update-Get-Caller-Function branch is still in progress

### ISSUE THREAD

**Issue by Okabe-Junya** [tsukuba-websci/rsurn#7]
## Problem

[Update-Get-Caller-Function branch](https://github.com/tsukuba-websci/rsurn/tree/Update-Get-Caller-Function) is still in progress.  If you need to merge these changes, you will need to create a PR. Or, if the branch is out of date, delete the branch

**Comment by Okabe-Junya** [comment]
@ciaran-regan-ie 

キリンさんがこのブランチを作成，実装していると思うので，アサインしても大丈夫ですか？？

---

I think that ciaran-san is creating and implementing this branch, is it ok if I assign it to you?

**Comment by mizoka** [comment]
はい。いいと思います。

2023年5月15日(月) 22:48 Junya Okabe ***@***.***>:

**Comment by ciaran-regan-ie** [comment]
@Okabe-Junya 
たしかに私に割り振るのはいいのですが、質問があります。このプロジェクトはどのように処理するのがベストなのでしょうか？私の研究は最後に合流させた方がいいのでしょうか？須田サンの研究を上書きするのは避けたい。もしかしたら、違うタグをつけることもできるかもしれません。どうなんでしょう？

Yes it is fine to assign to me, but I have a question. What is the best way to handle this project? Should my research be merged in at the end? I don't want to overwrite Suda sans research. Perhaps we could tag it differently? What do you think?

**Comment by Okabe-Junya** [comment]
@ciaran-regan-ie 

私はこのプロジェクトの詳細を把握していないので、岡先生、ななみさんと話し合ってください。

このブランチが3月から更新されていなかったので、PRを作成するか削除するかした方が良いかもしれません

---

I am not aware of the details of this project, so please discuss with Oka-Sensei and Nanami-san.

You may want to create or delete a PR since this branch has not been updated since March!

**Comment by Okabe-Junya** [comment]
However, since the changes are also significant, I think it would be good to be able to merge them.

**Comment by Okabe-Junya** [comment]
## Solution

過去のブランチをv0とし，破壊的な変更が入るので新しくデフォルトブランチをv1とした．

---

The past branch is set to v0, and the new default branch is set to v1 because it will undergo destructive changes.
